
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeCounterSample(Selebra.Flow.Sflow.SampleHeader,System.Byte[])~Selebra.Flow.Sflow.CounterSample")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeEthernetCounter(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.EthernetCounter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeExtendedRouter(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.ExtendedRouter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeExtendedSwitch(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.ExtendedSwitch")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeFlowDataHeader(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.FlowDataHeader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeFlowSample(Selebra.Flow.Sflow.SampleHeader,System.Byte[])~Selebra.Flow.Sflow.FlowSample")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeIfCounter(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.IfCounter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodePacketHeader(System.Byte[])~Selebra.Flow.Sflow.SflowPacket")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeProcessorCounter(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.ProcessorInformation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeSampledIPv4(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.SampledIPv4")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeSampledIPv6(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.SampledIPv6")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeSampleHeader(System.Byte[],System.Int32)~Selebra.Flow.Sflow.SampleHeader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeTokenRingCounter(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.TokenRingCounter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeVgCounter(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.VgCounter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeVlanCounter(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.VlanCounter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.Sflow.SflowDecoder.DecodeSampledEthernet(System.Byte[],Selebra.Flow.Sflow.RecordHeader)~Selebra.Flow.Sflow.SampledEthernet")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.TCPIP.EthernetHeaderDecoder.DecodeIcmpHeader(System.Byte[])~Selebra.Flow.TCPIP.EthernetHeader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.TCPIP.IcmpHeaderDecoder.DecodeIcmpHeader(System.Byte[])~Selebra.Flow.TCPIP.IcmpHeader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.TCPIP.TcpHeaderDecoder.DecodeTcpHeader(System.Byte[])~Selebra.Flow.TCPIP.TcpHeader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Selebra.Flow.TCPIP.UdpHeaderDecoder.DecodeUdpHeader(System.Byte[])~Selebra.Flow.TCPIP.UdpHeader")]